name: Основные клиент-серверные приложения в Java
headline: ключевые, слова
description: |
    В данном курсе узнаете о базовых концепцпиях и понятих необходимых для написание клеинт-серверной архитекруте. В дополнение к базовым аспектам будут завтронуты вопросо того, что такое REST API, а так же основы клиент-серверного взаимоействия современных систем.
goal: |
    Получить теоретические знание и практический опыт написания собственных распределенных клиент-серверных приложений
