name: Основные клиент-серверные приложения в Java
headline: client server architecture, client server interactions, network, cloud
description: |
    В данном курсе узнаете о базовых концепциях и понятиях, необходимых для написания клеинт-серверной архитекруты. В дополнение к базовым аспектам будут затронуты вопросы того, что такое REST API, а также основы клиент-серверного взаимодействия современных систем.
goal: |
    Получить теоретические знания и практический опыт написания собственных распределенных клиент-серверных приложений.
