name: Безопасность сайтов
headline: XSS, SQL-Injection
description: |
    Создание безопасных и надежных веб-приложений это тема, которую многие обходят стороной во время обучения. А от этого во многом зависит успешность и доверие пользователей.
goal: Познакомиться с основными способами взлома сайтов и кражи аккаунтов. Понять, как защищаться от подобных угроз.

# courses:
#     - name: 'Основы HTTP'
#       url: 'https://ru.hexlet.io/courses/http_protocol'
